### ISSUE TITLE
No Load() function for Rewarded Video

### ISSUE THREAD

**Issue by FuseGamesLLC** [YoYoGames/GMEXT-IronSource#1]
I am able to get a callback for ironsource_rewardedvideo_init(), but no callback for video ready or show. I noticed for interstitial there's a separate Load() function. Am I missing something or does there need to be a rewarded_video_load() as well? Thanks!

**Comment by FuseGamesLLC** [comment]
Hi, is there any update on a time line to upload a new version with the load() function included? Thanks!

**Comment by jzavala-YYG** [comment]
Previously we used automatic load for Rewarded Video ads, Currently we are using a manual load. now it's mandatory call ironsource_rewarded_video_load() to show Rewarded Video ads

**Comment by FuseGamesLLC** [comment]
> Previously we used automatic load for Rewarded Video ads, Currently we are using a manual load. now it's mandatory call ironsource_rewarded_video_load() to show Rewarded Video ads

That's the issue I was raising, there is no ironsource_rewarded_video_load() to call, that function isn't part of the included bundle like how ironsource_interstitial_load() is.

**Comment by jzavala-YYG** [comment]
> > Previously we used automatic load for Rewarded Video ads, Currently we are using a manual load. now it's mandatory call ironsource_rewarded_video_load() to show Rewarded Video ads
> 
> That's the issue I was raising, there is no ironsource_rewarded_video_load() to call, that function isn't part of the included bundle like how ironsource_interstitial_load() is.

Check last commits now is **_ironsource_rewarded_video_load()_** it's there. The extension worked correctly without it but now for consistence with other extensions and interstitial ad format we changed to manual mode for Rewarded Ad format

You can export the extension from this commit and should be presented da9124649f3dc23b97d9700f342442a9562c8abf

keep an eye in the callbacks type

**Comment by FuseGamesLLC** [comment]
> > > Previously we used automatic load for Rewarded Video ads, Currently we are using a manual load. now it's mandatory call ironsource_rewarded_video_load() to show Rewarded Video ads
> > 
> > 
> > That's the issue I was raising, there is no ironsource_rewarded_video_load() to call, that function isn't part of the included bundle like how ironsource_interstitial_load() is.
> 
> Check last commits now is **_ironsource_rewarded_video_load()_** it's there. The extension worked correctly without it but now for consistence with other extensions and interstitial ad format we changed to manual mode for Rewarded Ad format
> 
> You can export the extension from this commit and should be presented [da91246](https://github.com/YoYoGames/GMEXT-IronSource/commit/da9124649f3dc23b97d9700f342442a9562c8abf)
> 
> keep an eye in the callbacks type

Got it thank you so much for the quick reply!

I apologize but I'm a little lost in how to import the new version, I tried downloading the raw file and swapping copying the files into my project but it won't build, and I tried importing the project but can't seem to do that either. How do I update my older version with a version from github?

**Comment by jzavala-YYG** [comment]
First download or clone the repository locally, then open the GameMaker project and go to **_Tools_** -> **_Create Local Package_**, include the IronSource extension, press ok and save the package

Now open your GameMaker project, go to **_Tools_** -> **_Import Local Package_** and select the package created and select the extension

If you have any problem please let us know

Thanks

**Comment by jzavala-YYG** [comment]
You shouldn't use both extensions at same time, for that are the mediations

Delete one of the extensions and check which mediations are will use
