### ISSUE TITLE
Consent management support in extension?

### ISSUE THREAD

**Issue by ChopperKhan** [YoYoGames/GMEXT-IronSource#10]
I've taken a look at this extension and can't find anything regarding consent management in the sample project, or the documentation. How do we comply with the various legal requirements (GDPR, COPPA etc) when using this extension?
The Yoyo Admob extension has all this included and documented so seems odd it is missing from this one.

**Comment by jzavala-YYG** [comment]
Hello @ChopperKhan 

Under the information here:
https://developers.is.com/ironsource-mobile/general/making-sure-youre-compliant-post-gdpr/#step-1
You can use the Admob consent or create your own consent.

And following this link: https://developers.is.com/ironsource-mobile/android/regulation-advanced-settings/#step-1
I include the 2 functions that will allow you to create your own consent:

@YYBartT 
--------------------------------------------------------------------------------------
Enable the consent configuration, should be only set true if user consented
ironsource_set_consent(double enable)
--------------------------------------------------------------------------------------
Set an internal property to the IronSource system:
ironsource_set_metadata(key,value);

**Comment by Foxtrio** [comment]
> Hello @ChopperKhan
> 
> Under the information here: https://developers.is.com/ironsource-mobile/general/making-sure-youre-compliant-post-gdpr/#step-1 You can use the Admob consent or create your own consent.
> 
> And following this link: https://developers.is.com/ironsource-mobile/android/regulation-advanced-settings/#step-1 I include the 2 functions that will allow you to create your own consent:
> 
> @YYBartT
> 
> Enable the consent configuration, should be only set true if user consented **_ironsource_set_consent(double enable)_**
> 
> Set an internal property to the IronSource system: **_ironsource_set_metadata(key,value);_**

In my own implementation for another platform, I have used YYG's AdMob Extension for UMP SDK and my own implementation. UMP SDK is IAB compliant, and consents are automatically read by IAB compliant ad vendors(Ironsource is one of them)

This, however, raises the question whether YYG-AdMob Ext should be divided into two parts of UMP + AdMob Core since UMP SDK can be separately used.

**Comment by YYBartT** [comment]
Documented the new functions `ironsource_set_consent()` and `ironsource_set_metadata()`. The changes have been added to the [wiki](https://github.com/YoYoGames/GMEXT-IronSource/wiki).
