### ISSUE TITLE
ISOfferWallDelegate Error on iOS

### ISSUE THREAD

**Issue by GamePatty** [YoYoGames/GMEXT-IronSource#14]
Getting Error from IronSource Extension while compiling on iOS!

"GM_IOS/IronSource.Ext.v1.0.2/IronSource_Ext_v1_0_2/IronSource_Ext_v1_0_2/Game/iOSSource/IronSourceGM.h:13:35 No type or protocol named 'ISOfferwallDelegate'"

Try compiling the extension package itself and you will get this error!

Thanks

**Comment by DiasFranciscoA** [comment]
Fixed in release 1.1.0 thank you for the report
