### ISSUE TITLE
app is muted on iOS after video playback

### ISSUE THREAD

**Issue by kodaj25** [YoYoGames/GMEXT-IronSource#4]
IDE 2024.4.0.137
runtime 2024.4.0.168
build: VM for iOS

With the provided ironSource Demo project, when trying it on iOS devices, all sound is muted after playing a rewarded video.

### Steps to reproduce
1. Open ironSource Demo project
2. Add ironSource details (so you can play ads)
3. Add a sound resource
4. Add a button that will play the sound on press (or add the sound to one of the existing buttons)
5. Build for iOS
6. Play the sound
7. Play a rewarded video
8. Play the sound again -> it will be muted. same with music.

When going to the device's home screen and back into the app sound starts playing again.
We have tested this on various devices (iPhone, iPad, iOS 14, 15, 16)

**Comment by jzavala-YYG** [comment]
I can confirm this issue, probably we will need pause the whole app/game at show ads and resume at back to game

**Comment by jzavala-YYG** [comment]
ef09783518c802bb8b5a1e2a0d0fd0e7bf8af81d
