### ISSUE TITLE
Offerwall Implementation

### ISSUE THREAD

**Issue by Foxtrio** [YoYoGames/GMEXT-IronSource#9]
Hello,

I've seen that you have removed the **offerwall** option from the extension. Offerwall functionality is transferred to TapJoy after IronSource acquired the company. Therefore, IS expects you to use TapJoy SDK for offerwall functionality.

It would be helpful to have this optionality in the games. The code itself should be very similar to old IS Offerwall code, I think.

**Comment by Foxtrio** [comment]
Any updates on this. It would be nice to have this one 🙏

**Comment by jzavala-YYG** [comment]
@YYBartT 
https://ltv.tapjoy.com/sdk/api/java/com/tapjoy/Tapjoy.html
https://ltv.tapjoy.com/sdk/api/java/com/tapjoy/TJPlacement.html
https://ltv.tapjoy.com/sdk/api/java/com/tapjoy/TJPrivacyPolicy.html

--------------------------------------------------------------------------------------------

//Connects to the Tapjoy Server
void tapjoy_connect(double enable_logging,String user_id) 

			//Callback when connect is successful.
			type: tapjoy_on_connect_success
			
			//Callback when connect fails.
			type: tapjoy_on_connect_failure
			
			type: tapjoy_on_connect_warning
			message:

--------------------------------------------------------------------------------------------

//Enables or disables Tapjoy logging
void tapjoy_set_debug_enabled(double enabled)

--------------------------------------------------------------------------------------------

//Initializes a placement ad
void tapjoy_placement_init(String placement_name)

--------------------------------------------------------------------------------------------

//Send an event from the app to the server.
void tapjoy_placement_request_content(String placement_name)

		type tapjoy_on_request_success
		placement: placement name
		
		type: tapjoy_on_request_failure
		placement: placement name
		error: 
		
		//Called when a content for the given placement is ready to show.
		type: tapjoy_on_content_ready
		placement: placement name

--------------------------------------------------------------------------------------------

//Shows the content that was received from the server requesting content
void tapjoy_placement_show(String placement_name) 

		//Called when a content for the given placement is showing.
		type: tapjoy_on_content_show
		placement: placement name

		//Called when a content for the given placement is dismissed.
		type: tapjoy_on_content_dismiss
		placement: placement name

		//Called when a purchase has been requested.
		type: tapjoy_on_purchase_request
		placement: placement name

		//Called when a click event has occurred
		type: tapjoy_on_click
		placement: placement name

		//Called when a reward unlock has been requested.
		type: tapjoy_on_reward_request
		placement: placement name
		item_id:
		quantity: (double)

--------------------------------------------------------------------------------------------

//Whether or not the pre-loaded content for this placement has been cached and is ready to be presented
double tapjoy_placement_is_content_ready(String placement_name) 

--------------------------------------------------------------------------------------------

//Whether or not content for this placement has been returned and is ready to be presented
double tapjoy_placement_is_content_available(String placement_name) 

--------------------------------------------------------------------------------------------

//Spends virtual currency.
void tapjoy_spend_currency(double spendAmount) 
				type: tapjoy_on_spend_currency_response
				currency_name: string //The name of the virtual currency.
				balance: (double) //Currency balance after spend currency transaction.

				type: tapjoy_on_spend_currency_response_failure
				error: //The error message for a failed request.

--------------------------------------------------------------------------------------------

//Gets the virtual currency data from the server for this device. The data will be returned in a callback to onCurrencyBalanceResponse() to the class implementing the listener.
void tapjoy_get_currency_balance() 

				type: tapjoy_on_get_currency_balance_response
				currency_name: string //The name of the virtual currency.
				balance: (double) //Currency balance.

				type: tapjoy_on_get_currency_balance_response_failure
				error: //The error message for a failed request.

--------------------------------------------------------------------------------------------

//This is used for sending User's consent to behavioral advertising such as in the context of GDPR The consent value can be "0" (User has not provided consent), "1" (User has provided consent) or a daisybit string as suggested in IAB's Transparency and Consent Framework
void tapjoy_set_user_consent(double userConsent)

--------------------------------------------------------------------------------------------

//This can be used by the integrating App to indicate if the user falls in any of the GDPR applicable countries (European Economic Area).
void tapjoy_set_subject_to_gdpr(double subject_to_gdpr)

--------------------------------------------------------------------------------------------

//This is used for sending US Privacy value to behavioral advertising such as in the context of GDPR The value can be in IAB's US Privacy String Format consists of specification version to encode the string in number, explicit notice or opportunity to opt out in enum, opt-out sale in enum, LSPA covered transaction in enum .
//Suggested US Privacy String Format : https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/Version%201.0/US%20Privacy%20String.md#us-privacy-string-format
void tapjoy_set_us_privacy(String ccpa)

--------------------------------------------------------------------------------------------

//In the US, the Childrenâ€™s Online Privacy Protection Act (coppa) imposes certain requirements on operators of online services that (a) have actual knowledge that the connected user is a child under 13 years of age, or (b) operate services (including apps) that are directed to children under 13.
void tapjoy_set_below_consent_age(double below_consent_age)

**Comment by patrickrocheyoyo** [comment]
@YYBartT Could the above go into docs please?

**Comment by YYBartT** [comment]
The basic documentation for the Tapjoy functions has now been written.
